### ISSUE TITLE
Conda installation error

### ISSUE THREAD

**Issue by ellyyuyang** [HKU-BAL/MegaPath-Nano#1]
Hello,

Thanks for developing this tool! I was trying to download this tool and give it a try but I ran into error when installing following the conda path, and would be grateful if you could point to me how I could fix the error. Thanks!

So I followed the exact commands for the conda installation route until I ran into error messages. I ran into error messages when running the following command and I copy the error message below too: 

(mpn) XXX$ **pip install git+https://github.com/arpcard/rgi.git pyfaidx pyahocorasick seaborn pandarallel**

Collecting git+https://github.com/arpcard/rgi.git
  Cloning https://github.com/arpcard/rgi.git to /tmp/pip-req-build-v1yrqivr
    ERROR: Command errored out with exit status 1:
     command: /home/yangyu/.conda/envs/mpn/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-v1yrqivr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-v1yrqivr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7mo1k451
         cwd: /tmp/pip-req-build-v1yrqivr/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-v1yrqivr/setup.py", line 14, in <module>
        from app.settings import SOFTWARE_VERSION
      File "/tmp/pip-req-build-v1yrqivr/app/settings.py", line 7, in <module>
        from Bio.Alphabet import generic_dna
      File "/home/yangyu/.local/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
        "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
    ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I then ran the following command following the instruction in the error message:
(mpn) XXX$ **python setup.py egg_info**
python: can't open file 'setup.py': [Errno 2] No such file or directory

Much appreciated your help!

Regards,
Elly

**Comment by edwwlui** [comment]
Thanks for reporting the issue. I reproduced the issue with Biopython not in version of 1.72. As RGI requires the version of biopython equal to 1.72, please make sure that its version is correct. :)
